# Generated by Django 2.2.1 on 2019-05-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.AutoField(db_column='UID', max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='标题')),
                ('content', models.CharField(db_index=True, max_length=128, verbose_name='地址')),
                ('remark', models.CharField(blank=True, max_length=128, verbose_name='栏目')),
            ],
            options={
                'db_table': 'ArticleList',
            },
        ),
    ]
